# Generated by Django 5.1.1 on 2024-09-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_alter_measurement_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='photo',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='measurement/photos'),
        ),
    ]
