# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта 1
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Помидор",
  "description": "Лучшие помидоры на рынке"
}

###

# создание продукта 2
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Огурец",
  "description": "Лучшие огурцы на складе"
}

###

# создание продукта 3
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Свекла",
  "description": "Самая красная свекла на рынке"
}

###

# создание продукта 4
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Морковь",
  "description": "Самая сладкая на рынке"
}

###

# создание продукта 5
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Картошка",
  "description": "Превосходного качества"
}

###

# создание продукта 6
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Бананы",
  "description": "Хорошего качества"
}

###

# обновление продукта
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "Самые сочные и ароматные помидорки"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# создание склада 1
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "мой адрес не дом и не улица, мой адрес сегодня такой: www.ленинград-спб.ru3",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 3,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# создание склада 2
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Простенький склад",
  "positions": [
    {
      "product": 2,
      "quantity": 1250,
      "price": 110.50
    },
    {
      "product": 4,
      "quantity": 50,
      "price": 63.40
    }
  ]
}

###

# создание склада 3
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "Популярный склад",
  "positions": [
    {
      "product": 1,
      "quantity": 5250,
      "price": 46.50
    },
    {
      "product": 5,
      "quantity": 150,
      "price": 63.40
    }
  ]
}

###


# обновляем записи на складе
PATCH {{baseUrl}}/stocks/1/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 3,
      "quantity": 210,
      "price": 145
    }
  ]
}

###


# просмотр всех складов
GET {{baseUrl}}/stocks/1/
Content-Type: application/json

###

GET {{baseUrl}}/stocks/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=Карт
Content-Type: application/json

###

# получение продуктов
GET {{baseUrl}}/products/
Content-Type: application/json

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json

###


# ДОПОЛНИТЕЛЬНОЕ ЗАДАНИЕ...
# поиск складов, по наименованию или его части продукта
GET {{baseUrl}}/stocks/?search=Картошк
Content-Type: application/json

###

# поиск складов, по описанию продукта
GET {{baseUrl}}/stocks/?search=Сам
Content-Type: application/json

###